### ISSUE TITLE
Codepage error

### ISSUE THREAD

**Issue by isarantis** [deestan/srt2vtt#6]
Im getting this error when trying to execute your example script.
`C:\Users\user\Desktop\subs\node_modules\srt2vtt\node_modules\codepage\cputils.js:109
        mdb.length = 2 * len;
                   ^

TypeError: Cannot set property length of [object Object] which has only a getter
    at sbcs_d (C:\Users\user\Desktop\subs\node_modules\srt2vtt\node_modules\codepage\cputils.js:109:20)
    at Object.decode (C:\Users\user\Desktop\subs\node_modules\srt2vtt\node_modules\codepage\cputils.js:397:40)
    at Object.convertToUTF8 (C:\Users\user\Desktop\subs\node_modules\srt2vtt\encoding.js:93:46)
    at srt2vtt (C:\Users\user\Desktop\subs\node_modules\srt2vtt\index.js:45:12)
    at Object.<anonymous> (C:\Users\user\Desktop\subs\test.js:5:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)`

**Comment by deestan** [comment]
Hi! Thank you for the report.  I am assuming:

* using the example script given at the top of the README.md file.
* using `example.srt` from the project root as input.

I cannot reproduce your problem.  Can you give me more details?
